"""initial schema - all 27 tables

Revision ID: ca9e927a2346
Revises: 
Create Date: 2026-09-08 18:36:31.151347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca9e927a2346'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agencies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('agency_type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agencies_name'), 'agencies', ['name'], unique=False)
    op.create_table('locations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('constituency', sa.String(length=150), nullable=True),
    sa.Column('village_ward', sa.String(length=150), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_district'), 'locations', ['district'], unique=False)
    op.create_index(op.f('ix_locations_state'), 'locations', ['state'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('role_at_time', sa.String(length=100), nullable=True),
    sa.Column('action', sa.String(length=150), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('previous_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_table('imports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('uploaded_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'MAPPED', 'PREVIEWED', 'CONFIRMED', 'FAILED', name='importstatus'), nullable=False),
    sa.Column('column_mapping', sa.JSON(), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('valid_rows', sa.Integer(), nullable=False),
    sa.Column('error_rows', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('work_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('RECOMMENDED', 'SANCTIONED', 'IN_PROGRESS', 'STALLED', 'COMPLETED', 'CLOSED', name='projectstatus'), nullable=False),
    sa.Column('agency_id', sa.String(length=36), nullable=True),
    sa.Column('location_id', sa.String(length=36), nullable=True),
    sa.Column('recommendation_date', sa.Date(), nullable=True),
    sa.Column('sanction_date', sa.Date(), nullable=False),
    sa.Column('expected_completion_date', sa.Date(), nullable=True),
    sa.Column('actual_completion_date', sa.Date(), nullable=True),
    sa.Column('sanctioned_amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('estimated_cost', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit_of_measure', sa.String(length=50), nullable=True),
    sa.Column('asset_status', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_agency_id'), 'projects', ['agency_id'], unique=False)
    op.create_index(op.f('ix_projects_location_id'), 'projects', ['location_id'], unique=False)
    op.create_index(op.f('ix_projects_project_code'), 'projects', ['project_code'], unique=True)
    op.create_index(op.f('ix_projects_sanction_date'), 'projects', ['sanction_date'], unique=False)
    op.create_index('ix_projects_state_district_worktype', 'projects', ['work_type'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_index(op.f('ix_projects_work_type'), 'projects', ['work_type'], unique=False)
    op.create_table('risk_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('engine_version', sa.String(length=50), nullable=False),
    sa.Column('triggered_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('project_count', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role_name', sa.Enum('SYSTEM_ADMIN', 'MINISTRY_ADMIN', 'STATE_OFFICER', 'DISTRICT_REVIEWER', 'FIELD_VERIFIER', 'AUDITOR', 'CITIZEN', name='rolename'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_user_id'), 'roles', ['user_id'], unique=False)
    op.create_table('user_scopes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('scope_level', sa.Enum('NATIONAL', 'STATE', 'DISTRICT', 'WORK', 'CUSTOM', name='scopelevel'), nullable=False),
    sa.Column('scope_value', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_scopes_scope_value'), 'user_scopes', ['scope_value'], unique=False)
    op.create_index(op.f('ix_user_scopes_user_id'), 'user_scopes', ['user_id'], unique=False)
    op.create_table('anomalies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('risk_run_id', sa.String(length=36), nullable=False),
    sa.Column('anomaly_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['risk_run_id'], ['risk_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomalies_anomaly_type'), 'anomalies', ['anomaly_type'], unique=False)
    op.create_index(op.f('ix_anomalies_project_id'), 'anomalies', ['project_id'], unique=False)
    op.create_index(op.f('ix_anomalies_risk_run_id'), 'anomalies', ['risk_run_id'], unique=False)
    op.create_table('citizen_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('reference_id', sa.String(length=30), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reporter_contact', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citizen_reports_project_id'), 'citizen_reports', ['project_id'], unique=False)
    op.create_index(op.f('ix_citizen_reports_reference_id'), 'citizen_reports', ['reference_id'], unique=True)
    op.create_table('compliance_checks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('risk_run_id', sa.String(length=36), nullable=False),
    sa.Column('check_code', sa.String(length=20), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['risk_run_id'], ['risk_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_checks_project_id'), 'compliance_checks', ['project_id'], unique=False)
    op.create_index(op.f('ix_compliance_checks_risk_run_id'), 'compliance_checks', ['risk_run_id'], unique=False)
    op.create_table('duplicate_candidates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('candidate_project_id', sa.String(length=36), nullable=False),
    sa.Column('text_similarity', sa.Float(), nullable=False),
    sa.Column('geographic_similarity', sa.Float(), nullable=False),
    sa.Column('attribute_similarity', sa.Float(), nullable=False),
    sa.Column('combined_score', sa.Float(), nullable=False),
    sa.Column('ui_label', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_duplicate_candidates_candidate_project_id'), 'duplicate_candidates', ['candidate_project_id'], unique=False)
    op.create_index(op.f('ix_duplicate_candidates_project_id'), 'duplicate_candidates', ['project_id'], unique=False)
    op.create_table('import_rows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('import_id', sa.String(length=36), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('resulting_project_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['imports.id'], ),
    sa.ForeignKeyConstraint(['resulting_project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_rows_import_id'), 'import_rows', ['import_id'], unique=False)
    op.create_table('import_validation_errors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('import_id', sa.String(length=36), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('rule_code', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.Enum('ERROR', 'WARNING', 'INFO', name='validationseverity'), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('field_name', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['imports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_validation_errors_import_id'), 'import_validation_errors', ['import_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('payment_amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('payment_reference', sa.String(length=150), nullable=True),
    sa.Column('payment_type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_payment_date'), 'payments', ['payment_date'], unique=False)
    op.create_index(op.f('ix_payments_project_id'), 'payments', ['project_id'], unique=False)
    op.create_table('peer_benchmarks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('risk_run_id', sa.String(length=36), nullable=False),
    sa.Column('work_type', sa.String(length=100), nullable=False),
    sa.Column('group_level', sa.String(length=50), nullable=False),
    sa.Column('group_value', sa.String(length=150), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('median_cost', sa.Float(), nullable=False),
    sa.Column('iqr_low', sa.Float(), nullable=False),
    sa.Column('iqr_high', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['risk_run_id'], ['risk_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_peer_benchmarks_risk_run_id'), 'peer_benchmarks', ['risk_run_id'], unique=False)
    op.create_table('project_assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('asset_type', sa.String(length=150), nullable=True),
    sa.Column('condition', sa.String(length=100), nullable=True),
    sa.Column('verified_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_assets_project_id'), 'project_assets', ['project_id'], unique=False)
    op.create_table('project_financials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('utilized_amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_financials_project_id'), 'project_financials', ['project_id'], unique=False)
    op.create_table('project_progress',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('physical_progress_percent', sa.Float(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_progress_project_id'), 'project_progress', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_progress_report_date'), 'project_progress', ['report_date'], unique=False)
    op.create_table('project_relationships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('from_project_id', sa.String(length=36), nullable=False),
    sa.Column('to_project_id', sa.String(length=36), nullable=False),
    sa.Column('relationship_type', sa.String(length=100), nullable=False),
    sa.Column('strength', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['from_project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['to_project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_relationships_from_project_id'), 'project_relationships', ['from_project_id'], unique=False)
    op.create_index(op.f('ix_project_relationships_to_project_id'), 'project_relationships', ['to_project_id'], unique=False)
    op.create_table('risk_scores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('risk_run_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risklevel'), nullable=False),
    sa.Column('factors_computed_count', sa.Integer(), nullable=False),
    sa.Column('evidence_completeness_percent', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['risk_run_id'], ['risk_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_scores_project_id'), 'risk_scores', ['project_id'], unique=False)
    op.create_index(op.f('ix_risk_scores_risk_level'), 'risk_scores', ['risk_level'], unique=False)
    op.create_index(op.f('ix_risk_scores_risk_run_id'), 'risk_scores', ['risk_run_id'], unique=False)
    op.create_table('cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('risk_score_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('AI_FLAGGED', 'UNDER_REVIEW', 'FIELD_VERIFICATION_REQUESTED', 'FIELD_VERIFICATION_COMPLETED', 'DECISION_PENDING', 'NO_ISSUE_CLOSED', 'IRREGULARITY_ESCALATED', 'ACTION_TAKEN', 'INCONCLUSIVE_REVERIFY', 'CLOSED', name='casestatus'), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['risk_score_id'], ['risk_scores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_project_id'), 'cases', ['project_id'], unique=False)
    op.create_index(op.f('ix_cases_status'), 'cases', ['status'], unique=False)
    op.create_table('risk_factor_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('risk_score_id', sa.String(length=36), nullable=False),
    sa.Column('factor_code', sa.Enum('COST_DEVIATION', 'PROGRESS_EXPENDITURE_MISMATCH', 'DELAY_STALL', 'PAYMENT_ANOMALY', 'DUPLICATE_SIMILARITY', 'PEER_DEVIATION', 'ML_ANOMALY', name='factorcode'), nullable=False),
    sa.Column('raw_value', sa.Float(), nullable=True),
    sa.Column('normalized_score', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('contribution', sa.Float(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('detector_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['risk_score_id'], ['risk_scores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_factor_results_risk_score_id'), 'risk_factor_results', ['risk_score_id'], unique=False)
    op.create_table('case_assignments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('assigned_to_user_id', sa.String(length=36), nullable=False),
    sa.Column('assigned_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_assignments_case_id'), 'case_assignments', ['case_id'], unique=False)
    op.create_table('case_comments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('author_user_id', sa.String(length=36), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_comments_case_id'), 'case_comments', ['case_id'], unique=False)
    op.create_table('case_evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('evidence_category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('file_reference', sa.String(length=500), nullable=True),
    sa.Column('uploaded_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_evidence_case_id'), 'case_evidence', ['case_id'], unique=False)
    op.create_table('case_status_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('from_status', sa.Enum('AI_FLAGGED', 'UNDER_REVIEW', 'FIELD_VERIFICATION_REQUESTED', 'FIELD_VERIFICATION_COMPLETED', 'DECISION_PENDING', 'NO_ISSUE_CLOSED', 'IRREGULARITY_ESCALATED', 'ACTION_TAKEN', 'INCONCLUSIVE_REVERIFY', 'CLOSED', name='casestatus'), nullable=True),
    sa.Column('to_status', sa.Enum('AI_FLAGGED', 'UNDER_REVIEW', 'FIELD_VERIFICATION_REQUESTED', 'FIELD_VERIFICATION_COMPLETED', 'DECISION_PENDING', 'NO_ISSUE_CLOSED', 'IRREGULARITY_ESCALATED', 'ACTION_TAKEN', 'INCONCLUSIVE_REVERIFY', 'CLOSED', name='casestatus'), nullable=False),
    sa.Column('changed_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('remark', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_status_history_case_id'), 'case_status_history', ['case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_case_status_history_case_id'), table_name='case_status_history')
    op.drop_table('case_status_history')
    op.drop_index(op.f('ix_case_evidence_case_id'), table_name='case_evidence')
    op.drop_table('case_evidence')
    op.drop_index(op.f('ix_case_comments_case_id'), table_name='case_comments')
    op.drop_table('case_comments')
    op.drop_index(op.f('ix_case_assignments_case_id'), table_name='case_assignments')
    op.drop_table('case_assignments')
    op.drop_index(op.f('ix_risk_factor_results_risk_score_id'), table_name='risk_factor_results')
    op.drop_table('risk_factor_results')
    op.drop_index(op.f('ix_cases_status'), table_name='cases')
    op.drop_index(op.f('ix_cases_project_id'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_risk_scores_risk_run_id'), table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_risk_level'), table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_project_id'), table_name='risk_scores')
    op.drop_table('risk_scores')
    op.drop_index(op.f('ix_project_relationships_to_project_id'), table_name='project_relationships')
    op.drop_index(op.f('ix_project_relationships_from_project_id'), table_name='project_relationships')
    op.drop_table('project_relationships')
    op.drop_index(op.f('ix_project_progress_report_date'), table_name='project_progress')
    op.drop_index(op.f('ix_project_progress_project_id'), table_name='project_progress')
    op.drop_table('project_progress')
    op.drop_index(op.f('ix_project_financials_project_id'), table_name='project_financials')
    op.drop_table('project_financials')
    op.drop_index(op.f('ix_project_assets_project_id'), table_name='project_assets')
    op.drop_table('project_assets')
    op.drop_index(op.f('ix_peer_benchmarks_risk_run_id'), table_name='peer_benchmarks')
    op.drop_table('peer_benchmarks')
    op.drop_index(op.f('ix_payments_project_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_date'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_import_validation_errors_import_id'), table_name='import_validation_errors')
    op.drop_table('import_validation_errors')
    op.drop_index(op.f('ix_import_rows_import_id'), table_name='import_rows')
    op.drop_table('import_rows')
    op.drop_index(op.f('ix_duplicate_candidates_project_id'), table_name='duplicate_candidates')
    op.drop_index(op.f('ix_duplicate_candidates_candidate_project_id'), table_name='duplicate_candidates')
    op.drop_table('duplicate_candidates')
    op.drop_index(op.f('ix_compliance_checks_risk_run_id'), table_name='compliance_checks')
    op.drop_index(op.f('ix_compliance_checks_project_id'), table_name='compliance_checks')
    op.drop_table('compliance_checks')
    op.drop_index(op.f('ix_citizen_reports_reference_id'), table_name='citizen_reports')
    op.drop_index(op.f('ix_citizen_reports_project_id'), table_name='citizen_reports')
    op.drop_table('citizen_reports')
    op.drop_index(op.f('ix_anomalies_risk_run_id'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_project_id'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_anomaly_type'), table_name='anomalies')
    op.drop_table('anomalies')
    op.drop_index(op.f('ix_user_scopes_user_id'), table_name='user_scopes')
    op.drop_index(op.f('ix_user_scopes_scope_value'), table_name='user_scopes')
    op.drop_table('user_scopes')
    op.drop_index(op.f('ix_roles_user_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_table('risk_runs')
    op.drop_index(op.f('ix_projects_work_type'), table_name='projects')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index('ix_projects_state_district_worktype', table_name='projects')
    op.drop_index(op.f('ix_projects_sanction_date'), table_name='projects')
    op.drop_index(op.f('ix_projects_project_code'), table_name='projects')
    op.drop_index(op.f('ix_projects_location_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_agency_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_table('imports')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_locations_state'), table_name='locations')
    op.drop_index(op.f('ix_locations_district'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_agencies_name'), table_name='agencies')
    op.drop_table('agencies')
    # ### end Alembic commands ###
